spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: report_management
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

jwt:
  public-key: >
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1VbY9kO3vlwfXjK1aAfJI9mk64e3lsMJlDulpGJeC7XkvTl8ebmBS9FnD1yKD27pvlRs2WMUIJXDOycgAfti7TQMZUKBBg5ktNQHhpXWiTtf/T4hDa/sIUeZGDtoX3IqriOJIjsjfh/VP61EynFcWdEiAIJhQt798CgQAp4qZZgAwswidwKhib38/cpYheDQSWnKp7j9wiytc4JVkYdQcmUwD6l1GnM6LEXoFm98KwYYI3BmqLdd5uXBH8qG2C/xbhhyNKrhuYoGZ8GmduSmwtsRzCiAxAlosf9M0XJIydjyuCsSj+yS2VhOoFag9hKEUgHBLIXvDJNaSz1O/IOCfQIDAQAB
  expiration: 3600