spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  application:
    name: report_management

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

stub:
  base-url: http://localhost:8082/api/v1/reports

jwt:
  public-key-path: classpath:jwt/public_key.pem
  expiration: 3600

  spring:
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration