spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reportdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: report_management

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  public-key-path: classpath:jwt/public_key.pem
  expiration: 3600